on:
  push:
    branches:
      - master

name: check

jobs:
  check:
    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.2.0' 
